# Generated by Django 5.2.1 on 2025-05-14 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutritionist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Breve biografía o descripción del nutricionista', null=True)),
                ('education', models.CharField(blank=True, help_text='Formación académica', max_length=255, null=True)),
                ('specialties', models.CharField(blank=True, help_text='Áreas de especialización', max_length=255, null=True)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('languages', models.CharField(blank=True, help_text='Idiomas hablados', max_length=255, null=True)),
                ('accepts_new_patients', models.BooleanField(default=True)),
                ('max_patients', models.PositiveIntegerField(default=50, help_text='Máximo de pacientes activos permitidos')),
                ('session_duration_minutes', models.PositiveIntegerField(default=30)),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutritionist_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
