# Generated by Django 5.2.1 on 2025-05-14 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutritionists', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal_plan', models.TextField(help_text='Descripción general del plan de comidas.')),
                ('calories', models.PositiveIntegerField(help_text='Total de calorías diarias recomendadas.')),
                ('caloric_needs', models.IntegerField(help_text='Necesidades calóricas basales del paciente.')),
                ('protein', models.FloatField(blank=True, help_text='Cantidad recomendada de proteínas (gramos).', null=True)),
                ('carbs', models.FloatField(blank=True, help_text='Cantidad recomendada de carbohidratos (gramos).', null=True)),
                ('fats', models.FloatField(blank=True, help_text='Cantidad recomendada de grasas (gramos).', null=True)),
                ('pdf_plan', models.FileField(blank=True, help_text='Subir el plan nutricional completo en formato PDF.', null=True, upload_to='nutrition_plans/')),
                ('review_date', models.DateTimeField(blank=True, help_text='Fecha de revisión del plan nutricional.', null=True)),
                ('nutritionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_plans', to='nutritionists.nutritionist')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_plan', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Plan nutricional',
                'verbose_name_plural': 'Planes nutricionales',
            },
        ),
    ]
