# Generated by Django 5.2.1 on 2025-05-14 19:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutritionists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(help_text='Altura en cm')),
                ('current_weight', models.FloatField(help_text='Peso en kg')),
                ('waist_circumference', models.FloatField(blank=True, null=True)),
                ('hip_circumference', models.FloatField(blank=True, null=True)),
                ('goal_type', models.CharField(choices=[('Pérdida de peso', 'Pérdida de peso'), ('Ganar masa muscular', 'Ganar masa muscular'), ('Mantenimiento', 'Mantenimiento'), ('Mejorar hábitos', 'Mejorar hábitos'), ('Tratar condición médica', 'Tratar condición médica')], max_length=100)),
                ('medical_condition', models.CharField(blank=True, max_length=255, null=True)),
                ('preexisting_condition', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('digestive_issues', models.TextField(blank=True, null=True)),
                ('past_surgeries', models.TextField(blank=True, null=True)),
                ('work_activity', models.CharField(choices=[('Sedentario', 'Sedentario'), ('Activo', 'Activo'), ('Muy activo', 'Muy activo')], max_length=50)),
                ('exercise_frequency', models.PositiveIntegerField(blank=True, help_text='Veces por semana', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)])),
                ('exercise_type', models.CharField(blank=True, max_length=255, null=True)),
                ('fitness_level', models.CharField(choices=[('Bajo', 'Bajo'), ('Moderado', 'Moderado'), ('Alto', 'Alto')], max_length=50)),
                ('meals_per_day', models.IntegerField()),
                ('meal_schedule', models.TextField(blank=True, null=True)),
                ('dietary_preferences', models.CharField(blank=True, max_length=255, null=True)),
                ('favorite_foods', models.TextField(blank=True, null=True)),
                ('avoided_foods', models.TextField(blank=True, null=True)),
                ('water_intake', models.FloatField(help_text='Litros por día')),
                ('alcohol_caffeine_consumption', models.TextField(blank=True, null=True)),
                ('budget', models.FloatField(help_text='Presupuesto disponible para alimentación')),
                ('cooking_time', models.CharField(choices=[('Poco tiempo', 'Poco tiempo'), ('Tiempo medio', 'Tiempo medio'), ('Mucho tiempo', 'Mucho tiempo')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nutritionist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='nutritionists.nutritionist')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
